### ISSUE TITLE
Initial startup, create of new user

### ISSUE THREAD

**Issue by 3DEngelen** [MahmudJewel/fastapi-starter-kit#1]
Hi, 

This starting point for fastapi looks promising to me, however i have some questions, maybe the readme could be updated with this information.

1. Can you give some more details on how users are stored, what is the location of the DB file for example backup purposes?
2. Everyone can create a user and update the role of users, shouldn't this be only available for admin roles?
3. The passwords transferred to login are readable?

thx for feedback!

**Comment by MahmudJewel** [comment]
1- After migrating, database will be created in the root directory called **sqlite.db**.
You can set-up any database in the **app/core/database.py** file.
The bellow command will generate the db.
**_alembic upgrade head_**

2- For making easy structure, I did not applied RBAC(Role based access control). Anyway for applying RBAC, this repo may help you. https://github.com/MahmudJewel/FastAPI-Role-based-auth

3- Password will be saved as **hashed** password and you can read the hashed password.

For further query, feel free to ask me.
